title: Electric Jones
description: Game Sciences Research Lab

url: https://www.electricjones.org
baseurl: ""
paginate: 5
paginate_path: "/blog/page:num/"
#permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate, jemoji]
#gems: [jekyll-paginate, jemoji]

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Projects and Games
   url: /projects
 - title: Resources
   url: https://github.com/electricjones/awesome-game-studies
 - title: Blog and Articles
   url: /blog
 - title: Contact
   url: /contact

social:
   github: electricjones
#   twitter: brianmaierjr
#   facebook: brianmaierjr
   email: electricjoneslab@gmail.com

google_analytics: "UA-127061040-1"
