title: Electric Jones
description: My Research Site

url: https://electricjones.github.com
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate, jemoji]
paginate: 5

navigation:
 - title: Home
   url: /index.html
 - title: About
   url: /about
 - title: Projects and Games
   url: /projects
 - title: Resources
   url: https://github.com/electricjones/awesome-game-studies
 - title: Blog and Articles
   url: /blog
 - title: Contact
   url: /contact

social:
   github: electricjones
#   twitter: brianmaierjr
#   facebook: brianmaierjr
   email: electricjoneslab@gmail.com

google_analytics: "UA-58263416-1"
